### PR TITLE
In order to support file size over 4GB type off_t used for offset par…

### PR DESCRIPTION
**Pull request by bmarkiv**
…ameter has to be changed to size_t.

### CODE REVIEW

**Comment by ozra** [comment]
Sorry I didn't see this! It's so annoying that GitHub doesn't add issues made on own repos to the "participating"-list :-/ — that's the only one I check with frequency.

Thanks! I'll simply merge :-)

**Comment by bmarkiv** [comment]
Thanks!
Borys

**Comment by ozra** [comment]
I'm started working on the npm update, but I have a hard deadline, so I'll have to postpone it until sunday or so. I'm rewriting the LS to TypeScript, and doing some more cleanups also, before I update the package.

**Comment by ozra** [comment]
Terribly sorry, such a rush-hour that I forgot to publish the changes and push. Up now. Cheers.

**Comment by bmarkiv** [comment]
Thanks!

**Pull request merged**
